*** Settings ***
Suite Setup       Suite Setup Demo
Suite Teardown    Suite Teardown Demo
Force Tags        gRPC    Regression
Test Timeout      15 minutes
Library           SSHLibrary
Library           Collections
Library           OperatingSystem
Variables         ../constant.yaml
Resource          ../TestSuit/grpc_keywords.robot


*** Test Cases ****

GRPC_Test_01
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Transfer File With Specified Location Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_02
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Transfer File With Unspecified Location Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_03
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Transfer Multiple Files With Specified Location Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_04
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Receiver Compress Disabled Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_05
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Receiver Compress Enabled Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_06
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Checksum Validation Switchoff Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo

GRPC_Test_07
        [Documentation]    DESIGN STEPS
    ...
    ...    ============
    ...
    ...    gRPC Tool Testing Using Automation
    ...
    ...    Step1:
    ...
    ...    Login to Receiver VM and Execute the command to make receiver ready to accept the files.
    ...
    ...    Step 2:
    ...
    ...    Login to Sender VM and Execute the command to send a files
    ...
    ...    Step 3:
    ...
    ...    Check the eexcuted command is success or fail
    ...
    ...    Step4:
    ...
    ...    Login to Rceiver Command and check the file is recived at Receiver VM.
    ...
    ...    *ASSIGNEE=#####*
    [Tags]    NewFeature
    [Setup]    Test Setup Demo
    ${status}=    Checksum Validation Switchon Using gRPC Protocol Via SSH    ${sender}    ${reciver}
    log    ${status}
    Run Keyword If    '${status}' == '${False}'    fail    Test case is Failed
    [Teardown]    Test Teardown Demo